import streamlit as st

st.title("验证身份")
st.subheader("我们班后面放衣服和杂物的是什么？")
x = st.text_input("")
st.subheader("这个东西是什么时候做的？")
y = st.text_input(" ")
st.subheader("我们班的美称是什么？")
z = st.text_input("  ")
if x == "船" and y == "科技节" and z == "美好小二班":
    page = st.sidebar.title('电子相册')
    page = st.sidebar.radio('',['大合影','欧阳明静','李思陆','郭依鹭','唐铭祺','马婧媛','徐天朗','苏靖瑜','周巽龍','朱婉宁','王禹泽','房奕辰','辛沛轩','张靖澄','初泽琰','仵嫒旸','王择善','刘嘉言','李朗瑞','李择一','田济铉','潘昱澄','马一航','张玥涵','庄静翕','张欣煜','曹景腾','田岱伦','王婧萌','祝明坤','隋媛','刘一霖','尹艺霖','谢靖飞','黄子鉴','袁启航','谢柏安','张睦苒','李睿泽','张晨雨'])
    st.balloons()
    
    def page1():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("大合照")
        st.header("一年级开学典礼大合照")
        st.image("225.png")
        st.header("三年级开学典礼大合照")
        st.image("226.jpg")
        st.header("秋游大合影（中华民族园）")
        st.image("222.jpg")
        st.header("篮球联赛大合影")
        st.image("243.jpg")
        st.header("元旦联欢会大合影")
        st.image("1.jpg")
        
    
    def page2():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("欧阳明静")
        st.image("2.jpg")
        st.image("43.jpg")
        st.image("148.jpg")
        st.image("176.jpg")
        st.image("207.jpg")
        st.image("303.jpg")
        st.image("313.jpg")
        st.image("314.jpg")
        st.subheader("团体照")
        st.header("欧阳明静")
        st.image("3.jpg")
        st.image("4.jpg")
        st.image("5.jpg")
        st.image("6.jpg")
        st.image("7.jpg")
        st.image("8.jpg")
        st.image("9.jpg")
        st.image("10.jpg")
        st.image("11.jpg")
        st.image("12.jpg")
        st.image("13.jpg")
        st.image("134.jpg")
        st.image("177.jpg")
        st.image("221.jpg")
        st.image("304.jpg")
        st.image("307.jpg")
        st.image("310.jpg")
        st.image("311.jpg")
        st.image("318.jpg")
        st.image("319.jpg")
        st.image("320.jpg")
        st.image("322.jpg")
        st.image("324.jpg")
        st.image("326.jpg")
        st.image("328.jpg")
        st.image("329.jpg")
    
    def page3():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("李思陆")
        st.image("a.jpg")
        st.image("b.jpg")
        st.image("e.jpg")
        st.image("f.jpg")
        st.image("h.jpg")
        st.image("38.jpg")
        st.image("123.jpg")
        st.image("136.jpg")
        st.image("199.jpg")
        st.image("237.jpg")
        st.subheader("团体照")
        st.header("李思陆")
        st.image("g.jpg")
        st.image("221.jpg")
        st.image("233.jpg")
        st.image("332.jpg")
    
    
    
    
    def page4():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("郭依鹭")
        st.image("17.jpg")
        st.image("25.jpg")
        st.image("214.jpg")
        st.image("215.jpg")
        st.subheader("团体照")
        st.header("郭依鹭")
        st.image("14.jpg")
        st.image("15.jpg")
        st.image("16.jpg")
        st.image("18.jpg")
        st.image("20.jpg")
        st.image("21.jpg")
        st.image("22.jpg")
        st.image("26.jpg")
        st.image("27.jpg")
        st.image("28.jpg")
        st.image("29.jpg")
        st.image("33.jpg")
        st.image("34.jpg")
        st.image("35.jpg")
        st.image("36.jpg")
        st.image("150.jpg")
        st.image("209.jpg")
    
    def page6():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("唐铭祺")
        st.image("47.jpg")
        st.image("48.jpg")
        st.image("52.jpg")
        st.image("63.jpg")
        st.image("70.jpg")
        st.subheader("团体照")
        st.header("唐铭祺")
        st.image("50.jpg")
        st.image("51.jpg")
        st.image("53.jpg")
        st.image("55.jpg")
        st.image("62.jpg")
        st.image("64.jpg")
        st.image("65.jpg")
        st.image("66.jpg")
        st.image("67.jpg")
        st.image("93.jpg")
        st.image("95.jpg")
        st.image("180.jpg")
        st.image("181.jpg")
        st.subheader("班牌")
        st.image("49.jpg")
        st.image("56.jpg")
        st.image("57.jpg")
        st.image("58.jpg")
        st.image("59.jpg")
        st.image("60.jpg")
        st.image("61.jpg")
        st.subheader("教室")
        st.image("54.jpg")
        st.image("68.jpg")
        st.image("69.jpg")
    
    def page7():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("马婧媛")
        st.image("72.jpg")
        st.image("73.jpg")
        st.image("76.jpg")
        st.image("81.jpg")
        st.image("183.jpg")
        st.image("187.jpg")
        st.image("210.jpg")
        st.subheader("团体照")
        st.header("马婧媛")
        st.image("71.jpg")
        st.image("74.jpg")
        st.image("75.jpg")
        st.image("77.jpg")
        st.image("78.jpg")
        st.image("79.jpg")
        st.image("80.jpg")
        st.image("151.jpg")
        st.image("164.jpg")
        st.image("165.jpg")
        st.image("171.jpg")
        st.image("172.jpg")
        st.image("173.jpg")
        st.image("174.jpg")
        st.image("178.jpg")
        st.image("179.jpg")
        st.image("185.jpg")
        st.image("186.jpg")
        st.image("188.jpg")
        st.image("192.jpg")
        st.image("193.jpg")
        st.image("213.jpg")
        st.image("233.jpg")
        st.image("239.jpg")
        
    
    def page8():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("徐天朗")
        st.image("82.jpg")
        st.image("31.jpg")
        st.subheader("团体照")
        st.header("徐天朗")
        st.image("151.jpg") 
        st.image("213.jpg")
    
    def page9():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("苏靖瑜")
        st.image("19.jpg")
        st.image("130.jpg")
        st.image("131.jpg")
        st.subheader("团体照")
        st.header("苏靖瑜")
        st.image("9.jpg")
        st.image("16.jpg")
        st.image("20.jpg")
        st.image("22.jpg")
        st.image("27.jpg")
        st.image("28.jpg")
        st.image("29.jpg")
        st.image("33.jpg")
        st.image("34.jpg")
        st.image("35.jpg")
        st.image("36.jpg")
        st.image("71.jpg")
        st.image("77.jpg")
        st.image("78.jpg")
    
    def page10():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("周巽龍")
        st.image("23.jpg")
        st.image("30.jpg")
        st.subheader("团体照")
        st.header("周巽龍")
        st.image("15.jpg")
        st.image("297.jpg")
    
    def page11():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("朱婉宁")
        st.image("333.jpg")
        st.image("334.jpg")
        st.subheader("团体照")
        st.header("朱婉宁")
        st.image("8.jpg")
        st.image("14.jpg")
        st.image("15.jpg")
        st.image("16.jpg")
        st.image("18.jpg")
        st.image("20.jpg")
        st.image("26.jpg")
        st.image("32.jpg")
        st.image("34.jpg")
        st.image("35.jpg")
        st.image("223.jpg")
    
    def page12():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("王禹泽")
        st.image("40.jpg")
        st.image("44.jpg")
        st.subheader("团体照")
        st.header("王禹泽")
        st.image("125.jpg")
        st.image("101.jpg")
    
    def page13():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("房奕辰")
        st.image("84.jpg")
        st.image("109.jpg")
        st.subheader("团体照")
        st.header("房奕辰")
        st.image("83.jpg")
        st.image("93.jpg")
        st.image("103.jpg")
        st.image("108.jpg")
        st.image("114.jpg")
        st.image("138.jpg")
        st.image("139.jpg")
        st.image("198.jpg") 
        st.image("240.jpg")
    
    def page14():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("辛沛轩")
        st.image("85.jpg")
        st.image("c.jpg")
        st.image("289.jpg")
        st.subheader("团体照")
        st.header("辛沛轩")
        st.image("178.jpg")
        st.image("294.jpg")
        
    
    def page15():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("张靖澄")
        st.image("88.jpg")
        st.image("d.jpg")
        st.image("87.jpg")
        st.subheader("团体照")
        st.header("张靖澄")
        st.image("89.jpg") 
    
    def page16():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("初泽琰")
        st.image("86.jpg")
        st.image("295.jpg")
        st.subheader("团体照")
        st.header("初泽琰")
        st.image("89.jpg") 
        st.image("294.jpg")
        st.image("304.jpg")
    
    def page17():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("仵嫒旸")
        st.image("96.jpg")
        st.image("135.jpg")
        st.image("152.jpg")
        st.image("154.jpg")
        st.image("195.jpg")
        st.image("211.jpg")
        st.image("216.jpg")
        st.image("224.jpg")
        st.image("305.jpg")
        st.image("308.jpg")
        st.image("309.jpg")
        st.image("315.jpg")
        st.image("316.jpg")
        st.subheader("团体照")
        st.header("仵嫒旸")
        st.image("12.jpg") 
        st.image("14.jpg")
        st.image("21.jpg")
        st.image("39.jpg")
        st.image("91.jpg")
        st.image("92.jpg")
        st.image("g.jpg")
        st.image("134.jpg")
        st.image("223.jpg")
        st.image("311.jpg")
        st.image("317.jpg")
        st.image("318.jpg")
        st.image("321.jpg")
        st.image("323.jpg")
        st.image("325.jpg")
        st.image("327.jpg")
        st.image("330.jpg")
        st.image("331.jpg")
        
    
    def page18():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("王择善")
        st.image("97.jpg")
        st.image("98.jpg")
        st.image("117.jpg")
        st.image("137.jpg")
        st.image("244.jpg")
        st.subheader("团体照")
        st.header("王择善")
        st.image("50.jpg") 
        st.image("51.jpg")
        st.image("62.jpg")
        st.image("65.jpg")
        st.image("66.jpg")
        st.image("83.jpg")
        st.image("99.jpg")
        st.image("110.jpg")
        st.image("112.jpg")
        st.image("116.jpg")
        st.image("128.jpg")
        st.image("138.jpg")
        st.image("139.jpg")
        st.image("153.jpg")
        st.image("194.jpg")
        st.image("231.jpg")
    
    def page19():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("刘嘉言")
        st.image("100.jpg")
        st.image("230.jpg")
        st.image("245.jpg")
        st.subheader("团体照")
        st.header("刘嘉言")
        st.image("50.jpg") 
        st.image("51.jpg")
        st.image("55.jpg")
        st.image("62.jpg")
        st.image("65.jpg")
        st.image("66.jpg")
        st.image("99.jpg")
        st.image("116.jpg")
        st.image("180.jpg")
        st.image("181.jpg")
        
    def page20():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("李朗瑞")
        st.image("102.jpg")
        st.image("111.jpg")
        st.image("115.jpg")
        st.image("119.jpg")
        st.subheader("团体照")
        st.header("李朗瑞")
        st.image("110.jpg") 
        st.image("112.jpg")
        st.image("113.jpg")
        st.image("138.jpg")
        st.image("139.jpg")
        st.image("198.jpg")
            
    def page21():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("李择一")
        st.image("118.jpg")
        st.subheader("团体照")
        st.header("李择一")
        st.image("94.jpg")
        st.image("110.jpg") 
        st.image("112.jpg")
        st.image("113.jpg")
        st.image("125.jpg")
        st.image("127.jpg")

    def page22():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("田济铉")
        st.image("124.jpg")
        st.image("132.jpg")
        st.image("140.jpg")
        st.image("141.jpg")
        st.image("142.jpg")
        st.image("143.jpg")
        st.image("144.jpg")
        st.image("147.jpg")
        st.image("184.jpg")
        st.image("197.jpg")
        st.image("200.jpg")
        st.image("201.jpg")
        st.image("301.jpg")
        st.image("302.jpg")
        st.subheader("团体照")
        st.header("田济铉")
        st.image("150.jpg")
        st.image("79.jpg")
        st.image("75.jpg")
        st.image("74.jpg")
        st.image("3.jpg")
        st.image("171.jpg")
        st.image("172.jpg")
        st.image("173.jpg")
        st.image("177.jpg")
        st.image("185.jpg")
        st.image("186.jpg")
        st.image("188.jpg")
        st.image("190.jpg")
        st.image("192.jpg")
        st.image("193.jpg")
        st.image("209.jpg")
        st.image("239.jpg")
        st.image("240.jpg")
        st.image("242.jpg")
        st.image("307.jpg")

    def page23():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("潘昱澄")
        st.image("129.jpg")
        st.image("241.jpg")
        st.subheader("团体照")
        st.header("潘昱澄")
        st.image("153.jpg")
        st.image("112.jpg")
        st.image("95.jpg")
        st.image("194.jpg")
        st.image("198.jpg")

    def page24():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("马一航")
        st.image("145.jpg")
        st.image("273.jpg")
        st.image("274.jpg")
        st.image("275.jpg")
        st.subheader("团体照")
        st.header("马一航")
        st.image("33.jpg")

    def page25():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("张玥涵")
        st.image("149.jpg")
        st.image("166.jpg")
        st.image("170.jpg")
        st.image("175.jpg")
        st.image("182.jpg")
        st.image("191.jpg")
        st.image("238.jpg")
        st.image("306.jpg")
        st.subheader("团体照")
        st.header("张玥涵")
        st.image("80.jpg")
        st.image("75.jpg")
        st.image("74.jpg")
        st.image("164.jpg")
        st.image("165.jpg")
        st.image("171.jpg")
        st.image("172.jpg")
        st.image("173.jpg")
        st.image("175.jpg")
        st.image("178.jpg")
        st.image("179.jpg")
        st.image("186.jpg")
        st.image("188.jpg")
        st.image("190.jpg")
        st.image("192.jpg")
        st.image("193.jpg")
        st.image("239.jpg")
        
    def page26():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("庄静翕")
        st.image("196.jpg")
        st.image("203.jpg")
        st.image("204.jpg")
        st.image("205.jpg")
        st.image("208.jpg")
        st.image("218.jpg")
        st.image("219.jpg")
        st.image("220.jpg")
        st.image("234.jpg")
        st.image("235.jpg")
        st.image("236.jpg")
        st.image("250.jpg")
        st.subheader("团体照")
        st.header("庄静翕")
        st.image("217.jpg")

    def page27():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("张欣煜")
        st.image("160.jpg")
        st.image("161.jpg")
        st.image("162.jpg")
        st.image("163.jpg")
        st.subheader("团体照")
        st.header("张欣煜")
        st.image("211.jpg")
        st.image("256.jpg")
        st.image("257.jpg")
        st.image("258.jpg")

    def page28():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("曹景腾")
        st.image("227.jpg")
        st.subheader("团体照")
        st.header("曹景腾")
        st.image("126.jpg")
        st.image("127.jpg")
        st.image("121.jpg")
        st.image("122.jpg")
        st.image("120.jpg")
        st.image("66.jpg")
        st.image("64.jpg")
        st.image("62.jpg")
        st.image("51.jpg")
        st.image("50.jpg")

    def page29():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("田岱伦")
        st.image("232.jpg")
        st.image("248.jpg")
        st.image("249.jpg")
        st.subheader("团体照")
        st.header("田岱伦")
        st.image("231.jpg")
        st.image("139.jpg")
        st.image("138.jpg")
        st.image("122.jpg")
        st.image("121.jpg")
        st.image("120.jpg")
        st.image("6.jpg")

    def page30():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("王婧萌")
        st.image("251.jpg")
        st.image("276.jpg")
        st.subheader("团体照")
        st.header("王婧萌")
        st.image("101.jpg")
        st.image("45.jpg")
        st.image("37.jpg")

    def page31():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("祝明坤")
        st.image("252.jpg")
        st.image("300.jpg")
        st.subheader("团体照")
        st.header("祝明坤")
        st.image("212.jpg")

    def page32():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("隋媛")
        st.image("253.jpg")
        st.image("254.jpg")
        st.image("270.jpg")
        st.subheader("团体照")
        st.header("隋媛")
        st.image("223.jpg")
        st.image("91.jpg")
        st.image("36.jpg")
        st.image("35.jpg")
        st.image("34.jpg")
        st.image("32.jpg")
        st.image("28.jpg")
        st.image("27.jpg")
        st.image("26.jpg")
        st.image("22.jpg")
        st.image("21.jpg")
        st.image("16.jpg")
        st.image("15.jpg")
        st.image("14.jpg")

    def page33():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("刘一霖")
        st.image("259.jpg")
        st.image("290.jpg")
        st.image("291.jpg")
        st.image("292.jpg")
        st.image("293.jpg")
        st.subheader("团体照")
        st.header("刘一霖")
        st.image("262.jpg")
        st.image("277.jpg")
        st.image("278.jpg")
        st.image("279.jpg")
        st.image("280.jpg")
        st.image("258.jpg")
        st.image("257.jpg")
        st.image("256.jpg")

    def page34():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("尹艺霖")
        st.image("260.jpg")
        st.image("261.jpg")
        st.subheader("团体照")
        st.header("尹艺霖")
        st.image("128.jpg")

    def page35():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("谢靖飞")
        st.image("263.jpg")
        st.image("264.jpg")
        st.image("265.jpg")
        st.subheader("团体照")
        st.header("谢靖飞")
        st.image("93.jpg")
        st.image("296.jpg")
        st.image("297.jpg")
        st.image("299.jpg")

    def page36():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("黄子鉴")
        st.image("266.jpg")
        st.subheader("团体照")
        st.header("黄子鉴")
        st.image("198.jpg")
        st.image("296.jpg")
        st.image("299.jpg")

    def page37():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("袁启航")
        st.image("267.jpg")
        st.image("268.jpg")
        st.image("269.jpg")

    def page38():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("谢柏安")
        st.image("271.jpg")
        st.image("272.jpg")
        st.image("298.jpg")
        st.subheader("团体照")
        st.header("谢柏安")
        st.image("65.jpg")
        st.image("64.jpg")
        st.image("51.jpg")
        st.image("296.jpg")
        st.image("297.jpg")
        st.image("299.jpg")
        

    def page39():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("张睦苒")
        st.image("282.jpg")
        st.image("284.jpg")
        st.subheader("团体照")
        st.header("张睦苒")
        st.image("104.jpg")

    def page40():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("李睿泽")
        st.image("283.jpg")
        st.image("287.jpg")
        st.subheader("团体照")
        st.header("李睿泽")
        st.image("104.jpg")
        st.image("206.jpg")

    def page41():
        st.title("六（2）班电子相册")
        st.subheader("__________________________________________________")
        st.subheader("单人照")
        st.header("张晨雨")
        st.image("285.jpg")
        st.image("288.jpg")
        st.subheader("团体照")
        st.header("张晨雨")
        st.image("104.jpg")
        st.image("206.jpg")
        
    
    if page=="大合影":
        page1()
    
    if page=="欧阳明静":
        page2()
    
    if page=="李思陆":
        page3()
    
    if page=="郭依鹭":
        page4()

    
    if page=="唐铭祺":
        page6()
    
    if page=="马婧媛":
        page7()
    
    if page=="徐天朗":
        page8()
    
    if page=="苏靖瑜":
        page9()
    
    if page=="周巽龍":
        page10()
    
    if page=="朱婉宁":
        page11()
    
    if page=="王禹泽":
        page12()
    
    if page=="房奕辰":
        page13()
    
    if page=="辛沛轩":
        page14()
    
    if page=="张靖澄":
        page15()
    
    if page=="初泽琰":
        page16()
    
    if page=="仵嫒旸":
        page17()
    
    if page=="王择善":
        page18()
    
    if page=="刘嘉言":
        page19()

    if page=="李朗瑞":
        page20()
        
    if page=="李择一":
        page21()
        
    if page=="田济铉":
        page22()

    if page=="潘昱澄":
        page23()

    if page=="马一航":
        page24()

    if page=="张玥涵":
        page25()

    if page=="庄静翕":
        page26()

    if page=="张欣煜":
        page27()

    if page=="曹景腾":
        page28()

    if page=="田岱伦":
        page29()

    if page=="王婧萌":
        page30()
        
    if page=="祝明坤":
        page31()

    if page=="隋媛":
        page32()

    if page=="刘一霖":
        page33()

    if page=="尹艺霖":
        page34()

    if page=="谢靖飞":
        page35()

    if page=="黄子鉴":
        page36()

    if page=="袁启航":
        page37()

    if page=="谢柏安":
        page38()

    if page=="张睦苒":
        page39()

    if page=="李睿泽":
        page40()

    if page=="张晨雨":
        page41()